---
title: "Purpose of Report"
jupyter: python3
execute:
  freeze: false
---

Orange County respectfully acknowledges that every data point in this report represents a human life and the loss of a loved one. The purpose of this report is to help our communities, and their leaders, develop a deeper understanding of the circumstances surrounding drug overdose deaths to inform community level overdose prevention efforts. 

This report is a joint effort between the Office of the Medical Examiner, the Department of Mental Health, and the Department of Health in Orange County, NY. It provides data on overdose deaths and examines trends by drug type to provide local context to the current drug overdose landscape. It includes all overdose deaths in Orange County between January 1 and December 31, 2025.

The report aims to:
- Provide annual data on fatal overdoses to local planning partners
- Analyze trends in drug type, demographics, and location
- Inform community level overdose prevention and response programs

## Questions and Requests for Information

For any questions regarding this report or use of the data contained within, please contact the Orange County Department of Health, Division of Epidemiology and Public Health Planning:
- Phone: 845-291-2330
- Email: epidemiology@orangecountygov.com
